[package]
name = "skomakare"
version = "0.0.2"
authors = ["Kostyantyn Kovalskyy <kostelkow@gmail.com>"]

[dependencies]
glium = "0.14.0"
image = "*"
LambdaOxide = { git = "https://github.com/KostyaKow/LambdaOxide.git", version = "0.1.7" }

